### ISSUE TITLE
I have problems with requirements

### ISSUE THREAD

**Issue by X-n3t** [TheSecondSun/VTSCAN#3]
pip3 install -r requirements.txt
Collecting huepy
  Using cached huepy-1.2.1.tar.gz (15 kB)
ERROR: Could not find a version that satisfies the requirement json (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for json (from -r requirements.txt (line 2))

**Comment by X-n3t** [comment]
python3 vtscan.py -k ************0b0ca6b6041650676730a82d3040c************ -p /root/Descargas/love.exe
[*] Sent file to VT api
[*] Received response

Traceback (most recent call last):
  File "vtscan.py", line 104, in <module>
    main()
  File "vtscan.py", line 56, in main
    positives = int(resp.json()['positives'])
KeyError: 'positives'
